apiVersion: v1
kind: Pod
metadata:
  name: pp-nginx
  labels:
    env: pp
spec:
  containers:
  - name: pp-nginx
    image: nginx
    resources:
      requests:
        memory: "1.5Gi"
        cpu: "1"
      limits:
        memory: "2Gi"
        cpu: "2"
  priorityClassName: preprod-pc
