apiVersion: apps/v1
kind: Deployment
metadata:
  name: replicaset-1
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: fe
  template:
    metadata:
      labels:
        tier: fe
    spec:
      containers:
      - name: nginx
        image: nginx
