apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  securityContext:
    runAsUser: 1
  containers:
    - image: ubuntu
      name: container1
      command: ["sleep", "5000"]
      securityContext:
        runAsUser: 0
    - image: ubuntu
      name: container2
      command: ["sleep", "5000"]


# NOTE: Capabilities are just supported at container level. On the Pod level it won't work.
# You can use runAsUser and capabilities both under the same container.
