apiVersion: batch/v1
kind: Job
metadata:
  name: math-job
spec:
  template:
    spec:
      containers:
        - name: math-expr
          image: ubuntu
          command: ['expr', '3', '+', '33']
      restartPolicy: Never
