apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: sec-volume
          mountPath: /etc/sec-volume
  volumes:
    - name: sec-volume
      secret:
        secretName: test-secret


# Mount a volume in the container stating the secrets.
# Double check via logging into the pod 'k exec -it nginx bash' 
# View the files /etc/sec-volume{username,password}.

