apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: user_name
        valueFrom:
          secretKeyRef:
            name: rd-secret
            key: user_name
      - name: password
        valueFrom:
          secretKeyRef:
            name: rd-secret
            key: password
